version: '3.8'

services:
  nfl-standings:
    build: .
    container_name: nfl-standings
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER=true
      - OUTPUT_DIR=/app/output
    restart: on-failure
